# Generated by Django 5.0.4 on 2024-05-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigdb',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bigdb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='Image'),
        ),
    ]
